-- 蜡历 积己
CREATE USER SQLP_PRACTICE
IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- 鼻茄 何咯
GRANT CONNECT TO SQLP_PRACTICE;
GRANT RESOURCE TO SQLP_PRACTICE;
GRANT DBA TO SQLP_PRACTICE;